### ISSUE TITLE
I keep getting this log in my server logs

### ISSUE THREAD

**Issue by stantios** [Patbox/BanHammer#23]
I keep getting this in my server log and I'm not sure what it means or how to fix / prevent it:

[STDERR]: java.lang.IllegalArgumentException: Failed to parse webhook URL
[17:47:58] [Server thread/INFO]: [STDERR]:      at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:91)
[17:47:58] [Server thread/INFO]: [STDERR]:      at eu.pb4.banhammer.impl.config.Config.<init>(Config.java:112)
[17:47:58] [Server thread/INFO]: [STDERR]:      at eu.pb4.banhammer.impl.config.ConfigManager.loadConfig(ConfigManager.java:47)
[17:47:58] [Server thread/INFO]: [STDERR]:      at eu.pb4.banhammer.impl.BanHammerImpl.onServerStarting(BanHammerImpl.java:231)
[17:47:58] [Server thread/INFO]: [STDERR]:      at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
[17:47:58] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zla000$beforeSetupServer(MinecraftServer.java:4796)
[17:47:58] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
[17:47:58] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[17:47:58] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Patbox** [comment]
Your webhook url is invalid

**Comment by stantios** [comment]
What does that mean? Is it in the config?

**Comment by Patbox** [comment]
Yes, through it sounds like you didn't set it?

**Comment by stantios** [comment]
Is it this? 
![image](https://user-images.githubusercontent.com/98621617/202006488-49c3f868-591c-405d-bd6e-fe4027be6582.png)

**Comment by Patbox** [comment]
Yep, remove the `""`

**Comment by stantios** [comment]
> Yep, remove the `""`

This worked! Thank You
