### ISSUE TITLE
Bug that crashes server hard, PLEASE FIX.

### ISSUE THREAD

**Issue by xNotFlow** [Patbox/BanHammer#31]
`[10:11:07] [Server thread/INFO]: [STDERR]: eu.pb4.banhammer.impl.database.MiniConnectionPoolManager$TimeoutException: Timeout while waiting for a free database connection.
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.database.MiniConnectionPoolManager.getConnection2(MiniConnectionPoolManager.java:141)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.database.MiniConnectionPoolManager.getConnection(MiniConnectionPoolManager.java:132)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.database.AbstractSQLDatabase.removePunishment(AbstractSQLDatabase.java:198)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.BanHammerImpl.lambda$getPlayersPunishments$8(BanHammerImpl.java:226)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.database.AbstractSQLDatabase.getPunishments(AbstractSQLDatabase.java:100)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at eu.pb4.banhammer.impl.BanHammerImpl.getPlayersPunishments(BanHammerImpl.java:233)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3324.handler$zbm000$banHammer_checkIfBanned(class_3324.java:2027)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3324.method_14586(class_3324.java:448)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3248.method_14384(class_3248.java:102)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3248.redirect$zhc000$handlePlayerJoin(class_3248.java:1063)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3248.method_18784(class_3248.java:68)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10754(class_2535.java:248)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3242.method_14357(class_3242.java:183)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3813(class_3176.java:283)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
[10:11:07] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:11:07] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)>
[10:11:07] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.>`

**Comment by samuelh2005** [comment]
From my guess it looks like you have incorrectly configured your database. Without having the full log and config files there is no way for knowing.
